name: Build and publish site
run-name: 
on:
  push:
    branches:
      - main

jobs:
  Publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: mkdir full_build
      - run: cp -r index.html lab1 lab2 lab3 lab4 lab5 lab6 lab8 full_build
      - run: |
          cd lab7
          npm install
          npm run build
          mv ./build ../full_build/lab7
      - name: Publish build to gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./full_build
